### ISSUE TITLE
alternative for db-generated user ID

### ISSUE THREAD

**Issue by KerstenBreuer** [ghga-de/datameta#97]
For a REST endpoint like that `/api/users/{user_id}`, I currently use the user id generated by the database. That is fine but is a not very descriptive integer. The email would not be a good replacement as it not nicely integrates in a URL.

This is why it might be nicer if we would have a user alias that uniquely identifies a user in the database. This alias or username has to be set by the user upon registration.

Again, It is not absolutely necessary as db user IDs technically work fine. However, if we would want such a user alias, we should think of it now to avoid to much rewriting.

@lkuchenb, @GoliathMarks, @MoritzHahn1337

**Comment by GoliathMarks** [comment]
It would be advantageous for users because they are much more likely to remember their user id than some random number, particularly if that number is multiple digits. Additionally, it's unwise to reveal anything about the inner workings of the database, even something as seemingly innocuous as the number of a particular user. I think we should generated a unique id on the back end, but we should only have that ID used behind the scenes, and we can allow anything displayed to the user to happen via their chosen username.

**Comment by KerstenBreuer** [comment]
Yes, I fully agree, however, currently we only have email (which is not a good idea to embed in a  URL) and full name (which is not necessarily unique). So @lkuchenb should we think of implementing a unique username that a user has to choose upon registration?

**Comment by lkuchenb** [comment]
Fixed in #102
